### ISSUE TITLE
R.devices feedback

### ISSUE THREAD

**Issue by HenrikBengtsson** [frareb/inpdfr#1]
Hi, I'm glad to see you're using `R.devices`.  I just wanted to share a small FYI.

`devEval()` takes `name`, `tags` and `sep` and constructs the full name as `paste(c(name, tags), collapse=sep)`.  This means that instead of doing:

``` r
devEval(type = formatType, name = paste0("WORDCLOUD_",names(wordF)[i]), ...)
```

you could do:

``` r
devEval(type = formatType, name = "WORDCLOUD", tags = names(wordF)[i], sep = "_", ...)
```

FYI 2, the default is comma-separated tags (`sep=","`), so if skipped you would get file names such as `WORDCLOUD,hello.png`.  You/user can also set the default `sep` with `devOptions()`.

Feel free to close this "issue" at any time.

Henrik
(author of R.devices)

**Comment by frareb** [comment]
Thanks Henrik, 
I find using `paste0` in the `name` argument is easier to read. 
François
PS: congrats for your package, I use it everyday :+1:
